name: flutter_control
description: A new Flutter package.
version: 0.1.1
author: "Roman <ro.hornak@gmail.com>"
homepage: https://github.com/romanbase/flutter_control

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter


  # https://pub.dartlang.org/packages/shared_preferences
  shared_preferences: ">=0.1.0 <1.0.0"

flutter:

