name: flutter_control
description: Flutter Control is library to simply maintain App and State management. Provides some basic Widgets and Controllers to start with.
version: 0.10.2
author: "Roman <ro.hornak@gmail.com>"
homepage: https://github.com/romanbase/flutter_control

environment:
  sdk: ">=2.5.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dartlang.org/packages/shared_preferences
  shared_preferences: ">=0.1.0 <1.0.0"

flutter:

